#!/usr/bin/expect -f
set user root
set host 192.168.1.227
set password dinghuo123
set timeout -1

spawn ssh $user@$host
expect "*continue connecting (yes/no)?*"
send "yes\r"
expect "*assword:*"
send "$password\r"
interact
expect eof